name: howmuch
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.0.3
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.0
  dynamic_theme: ^1.0.1
  faker: ^1.3.0
  file_picker: ^2.1.5+1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  
  flutter:
    sdk: flutter
  
  flutter_bloc: ^6.0.5
  flutter_login: ^1.0.14
  flutter_sparkline: ^0.1.0
  get_it: ^5.0.6
  google_sign_in: ^4.5.3
  http: ^0.12.2
  intl: ^0.16.0
  line_awesome_icons: ^1.0.4+2
  logger: ^0.9.4
  moor: ^3.4.0
  path: ^1.7.0
  path_provider: ^1.6.24
  provider: ^4.3.2+2
  pull_to_refresh: ^1.6.4
  rxdart: ^0.25.0
  sqlite3_flutter_libs: ^0.3.0
  timelines: ^0.0.2+1
  undo: ^1.3.0+1  
  
  #syncfusion_flutter_charts: ^18.3.50  
  #collapsible_sidebar: ^1.0.5
  #flutter_slidable: ^0.5.7
  #flutter_material_color_picker: ^1.0.5
  #fluid_layout: ^0.1.0
  #flutter_iconpicker: ^2.2.2
  #toggle_switch: ^0.1.8
  #badges: ^1.1.4
  #giffy_dialog: ^1.8.0
  #dots_indicator: ^1.2.0

dev_dependencies:
  build_runner: ^1.10.4
  build_web_compilers: ^2.13.0
  
  flutter_test:
    sdk: flutter

  moor_generator: ^3.4.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  
  fonts:
    - family: Lato
      fonts:
        - asset: asset/font/lato/Lato-Thin.ttf
          weight: 100
        - asset: asset/font/lato/Lato-Light.ttf
          weight: 300
        - asset: asset/font/lato/Lato-Regular.ttf
          weight: 400
        - asset: asset/font/lato/Lato-Bold.ttf
          weight: 700
        - asset: asset/font/lato/Lato-Black.ttf
          weight: 900

    - family: Electrolize
      fonts:
        - asset: asset/font/electrolize/Electrolize-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: asset/font/montserrat/Montserrat-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
